### ISSUE TITLE
Want to contribute. Looking for ideas.

### ISSUE THREAD

**Issue by oddlyspaced** [UbiquitousLearning/mllm#102]
Hi,
I was going through the paper:
https://arxiv.org/pdf/2403.11805v1

and was researching around it. I reached the profile of Mengwei Xu (https://xumengwei.github.io/index.html) and landed here. I am highly interested in this project and would like to contribute. 

Is there anything that needs support or work that I can research and pick up?

I will be going through the code to see if anything can be updated or discussed.

Thanks a lot in advance!

**Comment by xumengwei** [comment]
Thanks for searching my profile :) In general mllm itself is an engineering-oriented system, atop which my team is validating and experimenting new research ideas. If you are passionate about on-device LLM, you can find things to do with mllm in our [Roadmap](https://ubiquitouslearning.github.io/mllm_website/roadmap/roadmap/). In general, I would suggest beginning with adding more model support (especially multimodal LLMs).

Regarding research, I probably cannot give any concrete ideas, but in general I believe LLM-as-a-system-service would open rich research opportunities in scheduling, reliability, persistence, and performance optimization. Have fun with it!

**Comment by oddlyspaced** [comment]
thanks a lot! I will go through the roadmap, and hopefully would be able to contribute to the project soon!
