### ISSUE TITLE
What is the difference between ggml and your project?

### ISSUE THREAD

**Issue by Subuday** [UbiquitousLearning/mllm#103]
Hi!
What is the difference between ggml and your project?

**Comment by xumengwei** [comment]
ggml is a great tensor library. mllm is first proposed as a standalone, end-to-end, mobile-friendly engine for LLM (especially multimodal LLMs). Atop mllm, our team (and perhaps more from other labs) is researching about on-device LLM optimization.

**Comment by Subuday** [comment]
But what about more technical differences? I am curious why you have not just used ggml autograd engine and decoded to write your own?

**Comment by xumengwei** [comment]
There're very limited technical differences across DNN/LLM engines (ggml, llama.cpp, MNN, tflite, etc). The initial intention in building mllm is just to have a lightweight LLM engine so we can easily modify and experiment with. Our team is actively researching around mobile LLM, and our future research prototypes (with "technical novelty") will be integrated into it.

**Comment by Subuday** [comment]
Okay, thanks for your answer.
