### ISSUE TITLE
Crash on Xiaomi 14(8gen3) with QNN

### ISSUE THREAD

**Issue by zhuipiaochen** [UbiquitousLearning/mllm#115]
When we run the main_gwen_npu on xiaomi14, it has the follow crash log:

![WechatIMG16036](https://github.com/user-attachments/assets/ff87f385-867b-4be0-bbcd-b019f780eb2a)

**Comment by liang1232018** [comment]
Thank you for your feedback.

It seems that the input datatype is wrong when starting to execute the NPU garphs. Have you ever changed the model datatype?

It's hard to tell what is the reason from your message provided. Could you turn on the `DEBUG` option in cmake and give more logs especially near the `[ERROR]`  and the information of your test device?
