### ISSUE TITLE
为什么预填充和解码不能都在 NPU 上运行？

### ISSUE THREAD

**Issue by yhwang-hub** [UbiquitousLearning/mllm#118]
我看了下代码，我的理解是prefill做的是预处理部分的工作，主要的推理是在decode部分完成，为什么代码里面是把prefill放在了npu上去执行，而重要的decode阶段要放在CPU上去执行？

**Comment by oreomaker** [comment]
The prefilling stage takes the prompt as input, initializes the KV Cache, and generates the first token, which is compute-bound. The decoding stage, on the other hand, takes each token as input, predicts the next token, and involves concatenating K and V from the KV Cache, making it memory-bound.

We utilize the NPU for the prefilling stage for two main reasons:
1. The NPU is better suited for compute-bound tasks, allowing us to optimize performance during the prefilling stage.
2. The QNN framework only supports static shape graphs. To use QNN for decoding, we would need to create an additional QNN graph, which would be resource-intensive.

Notably, the current NPU prefilling design already operates in a decoding manner when the 'c' parameter is set to 1. Therefore, it is feasible to have QNN handle both prefilling and decoding.

**Comment by yhwang-hub** [comment]
那为什么decode阶段不运行在NPU上而是运行在CPU上呢？

**Comment by oreomaker** [comment]
As I mentioned in the [reply](https://github.com/UbiquitousLearning/mllm/issues/118#issuecomment-2291412695), the decoding graph takes input with sequence length of 1, thus another QNN graph should be built, which is costly. 
As for the NPU, we decide to keep working on the prefilling stage to deliver the promised prefill speed first.
Current NPU prefilling of the auto-regressive like way is much slower than the CPU when used for decoding. So, the CPU decoding is just  to provide an end-to-end demo.

**Comment by zhuipiaochen** [comment]
那CPU占用率高吗，NPU的算力有没有得到充分释放呢，如果把CPU都打满了，是不是会影响其他程序运行，毕竟现实场景中端侧也会同时运行其他程序
