### ISSUE TITLE
./run_qwen_npu.sh失败

### ISSUE THREAD

**Issue by zcxo** [UbiquitousLearning/mllm#123]
./run_qwen_npu.sh失败，查看了下没有高通sdk目录（这个可以自己下载和修改），但是LLaMAPackage下没有build目录，所以缺少
LLaMAPackage_CPU.so和/libQnnLLaMAPackage_HTP.so。

LIBPATH=../src/backends/qnn/qualcomm_ai_engine_direct_220/
ANDR_LIB=$LIBPATH/lib/aarch64-android
OP_PATH=../src/backends/qnn/LLaMAOpPackageHtp/LLaMAPackage/build
DEST=/data/local/tmp/mllm/qnn-lib

adb push $ANDR_LIB/libQnnHtp.so $DEST
adb push $ANDR_LIB/libQnnHtpV75Stub.so $DEST
adb push $ANDR_LIB/libQnnHtpPrepare.so $DEST
adb push $ANDR_LIB/libQnnHtpProfilingReader.so $DEST
adb push $ANDR_LIB/libQnnHtpOptraceProfilingReader.so $DEST
adb push $ANDR_LIB/libQnnHtpV75CalculatorStub.so $DEST
adb push $LIBPATH/lib/hexagon-v75/unsigned/libQnnHtpV75Skel.so $DEST
adb push $OP_PATH/aarch64-android/libQnnLLaMAPackage.so $DEST/libQnnLLaMAPackage_CPU.so
adb push $OP_PATH/hexagon-v75/libQnnLLaMAPackage.so $DEST/libQnnLLaMAPackage_HTP.so

**Comment by Ethan-a2** [comment]
https://github.com/UbiquitousLearning/mllm/blob/main/src/backends/qnn/README.md#op-package-compile
