### ISSUE TITLE
./run_qwen-npu.sh failed

### ISSUE THREAD

**Issue by zcxo** [UbiquitousLearning/mllm#124]
./run_qwen-npu.sh failed. I checked and found that there is no Qualcomm SDK directory (which can be downloaded and modified by myself), but there is no build directory under LLaMAPacket, so it is missing
LLaMAPackage_CPU.so and/libQnLLAMPackage_CTP.so.

LIBPATH=../src/backends/qnn/qualcomm_ai_engine_direct_220/
ANDR_LIB=$LIBPATH/lib/aarch64-android
OP_PATH=../src/backends/qnn/LLaMAOpPackageHtp/LLaMAPackage/build
DEST=/data/local/tmp/mllm/qnn-lib

adb push $ANDR_LIB/libQnnHtp.so $DEST
adb push $ANDR_LIB/libQnnHtpV75Stub.so $DEST
adb push $ANDR_LIB/libQnnHtpPrepare.so $DEST
adb push $ANDR_LIB/libQnnHtpProfilingReader.so $DEST
adb push $ANDR_LIB/libQnnHtpOptraceProfilingReader.so $DEST
adb push $ANDR_LIB/libQnnHtpV75CalculatorStub.so $DEST
adb push $LIBPATH/lib/hexagon-v75/unsigned/libQnnHtpV75Skel.so $DEST
adb push $OP_PATH/aarch64-android/libQnnLLaMAPackage.so $DEST/libQnnLLaMAPackage_CPU.so
adb push $OP_PATH/hexagon-v75/libQnnLLaMAPackage.so $DEST/libQnnLLaMAPackage_HTP.so

**Comment by oreomaker** [comment]
Have you performed the [QNN Op Package Compiling](https://github.com/UbiquitousLearning/mllm/blob/main/src/backends/qnn/README.md)? After setting up the QNN env, you should compile the QNN Op Package first.

**Comment by zcxo** [comment]
Get 。 Thanks!
