### ISSUE TITLE
./bin/main_qwen_npu  fail

### ISSUE THREAD

**Issue by zcxo** [UbiquitousLearning/mllm#125]
你好！
请教如下问题如何解决：

执行如下命令失败：
phone:/data/local/tmp/mllm/bin # ls -l ../qnn-lib/                                                                                                                                                      
total 42968
-rwxrwxrwx 1 root root  1561544 2024-08-23 16:52 libQnnHtp.so
-rwxrwxrwx 1 root root   624648 2024-08-23 16:52 libQnnHtpOptraceProfilingReader.so
-rwxrwxrwx 1 root root 26967048 2024-08-23 16:52 libQnnHtpPrepare.so
-rwxrwxrwx 1 root root   507752 2024-08-23 16:52 libQnnHtpProfilingReader.so
-rwxrwxrwx 1 root root     6968 2024-08-23 16:52 libQnnHtpV75CalculatorStub.so
-rwxrwxrwx 1 root root 11682072 2024-08-23 16:52 libQnnHtpV75Skel.so
-rwxrwxrwx 1 root root   290664 2024-08-23 16:52 libQnnHtpV75Stub.so
-rwxrwxrwx 1 root root  1742656 2024-08-23 17:28 libQnnLLaMAPackage_CPU.so
-rwxrwxrwx 1 root root   561552 2024-08-23 17:29 libQnnLLaMAPackage_HTP.so

phone:/data/local/tmp/mllm/bin # ./main_qwen_npu -s 64 -c 1                                                                                                                                             
     0.1ms [ ERROR ] Unable to find a valid interface.
Error initializing QNN Function Pointers
1|phone:/data/local/tmp/mllm/bin # 
                                                                                                                  

谢谢。

**Comment by zcxo** [comment]
到bin目录执行，变为新的错误 merge file is broken：

phone:/data/local/tmp/mllm/bin # ./main_qwen_npu  -s 64 -c 1                                                                                                                                            
merge file is broken
phone:/data/local/tmp/mllm/bin #

**Comment by zcxo** [comment]
NDK  版本：25.1.8937393
qnn sdk版本：2.20.0.240223
HexagonSDK:5.5.0.1

**Comment by guoguo1314** [comment]
遇到同样的问题了，QNN SDK是v2.36版本，高于2.14，请问这个怎么解决的？

**Comment by guoguo1314** [comment]
Qualcomm AI Engine Direct SDK (QNN SDK):2.31.0.250130
qualcomm_neural_processing_sdk:2.21.0
Hexagon_SDK:5.5.5.0
ndk:25.1
依然会出现这个错误
```
RE5C4FL1:/data/local/tmp/mllm/bin $ ./demo_qwen_npu -m ../models/qwen-1.5-1.8b-chat-int8.mllm
[INFO] Mon Jul 28 18:51:12 2025 [/home/lyg/Codes/mllm/src/backends/qnn/QNNBackend.cpp:118] Backend: libQnnHtp.so
[ERROR] Mon Jul 28 18:51:12 2025 [/home/lyg/Codes/mllm/src/backends/qnn/Utils/DynamicLoadUtil.cpp:85] Unable to find a valid interface.
Error initializing QNN Function Pointers
```
