### ISSUE TITLE
运行时出现merge file is broken

### ISSUE THREAD

**Issue by mailonghua** [UbiquitousLearning/mllm#133]
运行时出现如下问题：
$ adb shell "cd /data/local/tmp/mllm/bin && export LD_LIBRARY_PATH=/data/local/tmp/mllm/qnn-lib && export ADSP_LIBRARY_PATH=/data/local/tmp/mllm/qnn-lib && ./main_qwen_npu -s 64 -c 1"                                                                                     
merge file is broken

**Comment by chenghuaWang** [comment]
The error is occurred here 

https://github.com/UbiquitousLearning/mllm/blob/4f6da8d48d8e03a2cba863a64a93c16ff8a29259/src/models/qwen/tokenization_qwen.hpp#L84

Did you push the merge file to your device before running it?

**Comment by mailonghua** [comment]
> The error is occurred here
> 
> https://github.com/UbiquitousLearning/mllm/blob/4f6da8d48d8e03a2cba863a64a93c16ff8a29259/src/models/qwen/tokenization_qwen.hpp#L84
> 
> Did you push the merge file to your device before running it?

感谢回复，确实是忘记将qwen_merges.txt进行Push

**Comment by GothicFox** [comment]
> > The error is occurred here
> > https://github.com/UbiquitousLearning/mllm/blob/4f6da8d48d8e03a2cba863a64a93c16ff8a29259/src/models/qwen/tokenization_qwen.hpp#L84
> > 
> > Did you push the merge file to your device before running it?
> 
> 感谢回复，确实是忘记将qwen_merges.txt进行Push

您好，请教下这个merge file是什么？在哪里？我在工程中好像没看到qwen_merges.txt这个文件，感谢感谢

**Comment by enguang2** [comment]
> The error is occurred here
> 
> [mllm/src/models/qwen/tokenization_qwen.hpp](https://github.com/UbiquitousLearning/mllm/blob/4f6da8d48d8e03a2cba863a64a93c16ff8a29259/src/models/qwen/tokenization_qwen.hpp#L84)
> 
> Line 84 in [4f6da8d](/UbiquitousLearning/mllm/commit/4f6da8d48d8e03a2cba863a64a93c16ff8a29259)
> 
>  std::cout << "merge file is broken\n"; 
> Did you push the merge file to your device before running it?

I have encountered same problem, I add `adb push ../vocab/qwen_merges.txt /data/local/tmp/mllm/vocab` in the run_qwen_npu.sh script and it crashed with a new error `(base) ds@ds-OptiPlex-9020:~/Research/mllm/scripts$ ./run_qwen_npu.sh 
mkdir: '/data/local/tmp/mllm': File exists
mkdir: '/data/local/tmp/mllm/bin': File exists
mkdir: '/data/local/tmp/mllm/models': File exists
mkdir: '/data/local/tmp/mllm/vocab': File exists
mkdir: '/data/local/tmp/mllm/qnn-lib': File exists
../vocab/qwen_merges.txt: 1 file pushed. 28.0 MB/s (1671839 bytes in 0.057s)
../vocab/qwen_vocab.mllm: 1 file pushed. 32.2 MB/s (3189278 bytes in 0.094s)
../bin-arm/main_qwen_npu: 1 file pushed. 32.4 MB/s (92188384 bytes in 2.716s)
../models/qwen-1.5-1.8b-chat-int8.mllm: 1 file pushed. 32.4 MB/s (3704200454 bytes in 109.049s)
../models/qwen-1.5-1.8b-chat-q4k.mllm: 1 file pushed. 31.5 MB/s (3059623428 bytes in 92.772s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtp.so: 1 file pushed. 29.0 MB/s (1869824 bytes in 0.062s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtpV75Stub.so: 1 file pushed. 23.4 MB/s (444688 bytes in 0.018s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtpPrepare.so: 1 file pushed. 31.5 MB/s (44449848 bytes in 1.347s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtpProfilingReader.so: 1 file pushed. 26.3 MB/s (578656 bytes in 0.021s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtpOptraceProfilingReader.so: 1 file pushed. 31.2 MB/s (2447792 bytes in 0.075s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/aarch64-android/libQnnHtpV75CalculatorStub.so: 1 file pushed. 0.8 MB/s (8168 bytes in 0.010s)
../src/backends/qnn/qualcomm_ai_engine_direct_220//lib/hexagon-v75/unsigned/libQnnHtpV75Skel.so: 1 file pushed. 30.9 MB/s (8282212 bytes in 0.256s)
../src/backends/qnn/LLaMAOpPackageHtp/LLaMAPackage/build/aarch64-android/libQnnLLaMAPackage.so: 1 file pushed. 28.6 MB/s (1478872 bytes in 0.049s)
../src/backends/qnn/LLaMAOpPackageHtp/LLaMAPackage/build/hexagon-v75/libQnnLLaMAPackage.so: 1 file pushed. 24.8 MB/s (820016 bytes in 0.032s)
[INFO] Wed Feb 12 19:54:19 2025 [/home/ds/Research/mllm/src/backends/qnn/QNNBackend.cpp:120] Backend: libQnnHtp.so
[INFO] Wed Feb 12 19:54:19 2025 [/home/ds/Research/mllm/src/backends/qnn/QNNBackend.cpp:147] Backend        build version: v2.27.0.240926142112_100894
[INFO] Wed Feb 12 19:54:19 2025 [/home/ds/Research/mllm/src/backends/qnn/QNNBackend.cpp:170] Initialize Backend Returned Status = 0
[INFO] Wed Feb 12 19:54:19 2025 [/home/ds/Research/mllm/src/backends/qnn/QNNBackend.cpp:634] Registered Op Package: libQnnLLaMAPackage_CPU.so and interface provider: LLaMAPackageInterfaceProvider
[INFO] Wed Feb 12 19:54:19 2025 [/home/ds/Research/mllm/src/backends/qnn/QNNBackend.cpp:634] Registered Op Package: libQnnLLaMAPackage_HTP.so and interface provider: LLaMAPackageInterfaceProvider
Load model: 2.03733 s
Load model: 1.29108 s
Load model: 4.29538 s
  7804.4ms [ ERROR ] Number of input elements 262144 does not match number of output elements 0.

  7804.4ms [ ERROR ] Op specific validation failed.

     0.0ms [ ERROR ]  <E> validateNativeOps master op validator model.layers.0.self_attn.ires_split-00_view_:qti.aisw:Reshape failed 3110

     0.0ms [ ERROR ]  <E> QnnBackend_validateOpConfig failed 3110

     0.0ms [ ERROR ]  <E> Failed to validate op model.layers.0.self_attn.ires_split-00_view_ with error 0xc26

[ ERROR ] QnnModel::addNode() validating node model.layers.0.self_attn.ires_split-00_view_ failed.
[ ERROR ] qnnModels_[qnnModelIndex_].addNode( QNN_OPCONFIG_VERSION_1, name.c_str(), packageName.c_str(), nodeType.c_str(), paramsPtr, params.size(), inputTensorNames, inputTensorNames.size(), outputTensors.data(), outputTensors.size() ) expected MODEL_NO_ERROR, got MODEL_GRAPH_ERROR
`
Can you help check it out?

**Comment by chenghuaWang** [comment]
cc @oreomaker

**Comment by oreomaker** [comment]
It seems that you have the QNN SDK version of 2.27, the Op Package under src/backends/qnn/LLaMAOpPackageHtp/LLaMAPackage need to be re-compiled and push to the device. @enguang2
