### ISSUE TITLE
Failed to allocate memory error on Galaxy S24 NPU

### ISSUE THREAD

**Issue by gingerly** [UbiquitousLearning/mllm#134]
Hello,
Thank you for sharing your valuable code with the community. 
After compiling and copying all the files, I was trying to run the qwen npu model on Galaxy S24 phone with Qualcomm Snapdragon Gen3 in the following way in termux:
`export LD_LIBRARY_PATH=../qnn-lib && export ADSP_LIBRARY_PATH=../qnn-lib && ./main_qwen_npu -s 64 -c 1 `

However, I got these errors:
```
0.0ms [ ERROR ]  <E> Failed to allocate memory
0.0ms [ ERROR ]  <E> Failed to create transport for device, error: 4000
0.0ms [ ERROR ]  <E> Failed to load skel, error: 4000
0.0ms [ ERROR ]  <E> Transport layer setup failed: 14001
0.0ms [ ERROR ]  <E> Failed to parse default platform info: 14001
0.0ms [ ERROR ]  <E> Failed to load default platform info: 14001
0.0ms [ ERROR ]  <E> Failed to parse platform config: 14001
0.7ms [ ERROR ] Failed to create device
0.7ms [ ERROR ] Device Creation failure
```

Also note that I tried to run `./SystemMemoryTest` and got an error:
``` 
Pointer tag for 0x5850f42340 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
Aborted
```
Any help regarding this would be much appreciated, thanks!

qnn sdk：2.20.0.240223
HexagonSDK: 5.5.0.1
SoC: Snapdragon 8gen3
NDK: 27.0.12077973

**Comment by oreomaker** [comment]
When building the QNN graph, QNN will allocate memory for static weights and IO tensors, which will be larger than 8GB and    the total memory will be about 16GB. It may be related to the 8/12GB memory of the S24.
