### ISSUE TITLE
Using Qwen-2.0

### ISSUE THREAD

**Issue by KAIWEILIUCC** [UbiquitousLearning/mllm#137]
I am trying to use Owen-2.0 in mllm. I converted the model, vocab using the given tools. However, the outputs of Owen-2.0 was garbled. Do I need to do any further modification on the code of mllm?

**Comment by chenghuaWang** [comment]
The current version of Qwen supported by mllm is v1.5. IIRC, both Qwen2 and Qwen1.5 are based on the Llama model, and they are largely similar. The primary distinction lies in their configuration settings. See:

v1.5: https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat/blob/main/config.json
v2.0: https://huggingface.co/Qwen/Qwen2-0.5B-Instruct/blob/main/config.json

![image](https://github.com/user-attachments/assets/9ae25b30-9437-434f-972f-1f958bc4f219)

U should modify the configuration file of Qwen https://github.com/UbiquitousLearning/mllm/blob/main/src/models/qwen/configuration_qwen.hpp .

**Comment by KAIWEILIUCC** [comment]
Thanks a lot!
