### ISSUE TITLE
where is bin folder?

### ISSUE THREAD

**Issue by siz0001** [UbiquitousLearning/mllm#138]
hello, would you please help me?
I wanna quantize gemma-ko-2b model, but cannot find bin folder.

`cd bin`
`./quantize model.mllm model_q4_k.mllm Q4_K`

and why the size of mllm model is 2 times larger then original safetensor file size?

**Comment by chenghuaWang** [comment]
For the first question: You need to compile the mllm project, after which the quantized executable file will be generated. For the second question, the mllm model directly converted stores data in fp32 format, whereas the safetensor you downloaded is in fp16 format, hence it is twice the size.

**Comment by siz0001** [comment]
thank you for your quick reply, what is compile mean? would you please explain more?

**Comment by chenghuaWang** [comment]
Pls use the following command to compile the complete mllm project before using the convert model
```sh
cd scripts
./build.sh
```

**Comment by siz0001** [comment]
thank you bro.
国庆节快乐！

**Comment by chenghuaWang** [comment]
It might be an Out of Memory issue. How much DRAM does your machine have? The quantization process can consume a significant amount of memory.

**Comment by siz0001** [comment]
It was indeed a memory issue. Both model conversion and quantization went smoothly after upgrading the DRAM to 64GB. Thank you.
