### ISSUE TITLE
Error on Xiaomi 14(8gen3) with QNN

### ISSUE THREAD

**Issue by ustcsq** [UbiquitousLearning/mllm#153]
QNN alloc size: 4194304
QNN alloc size: 262144
model.layers.0.self_attn.ires_split-00_view_is QNN INT8 op 
     0.0ms [ ERROR ]  <E> Tensor name InceptionV3_InceptionV3_Conv2d_1a_3x3_Conv2D_stride already exists in the graph.

[ ERROR ] QnnModel::addTensor() Creating tensor for node: model.layers.0.self_attn.k_proj.linearint8, tensorName: InceptionV3_InceptionV3_Conv2d_1a_3x3_Conv2D_stride.
[ ERROR ] QnnModel::addNode() addTensor() failed for tensor param InceptionV3_InceptionV3_Conv2d_1a_3x3_Conv2D_stride on node model.layers.0.self_attn.k_proj.linearint8.
[ ERROR ] qnnModels_[qnnModelIndex_].addNode( QNN_OPCONFIG_VERSION_1, name.c_str(), packageName.c_str(), nodeType.c_str(), paramsPtr, params.size(), inputTensorNames, inputTensorNames.size(), outputTensors.data(), outputTensors.size() ) expected MODEL_NO_ERROR, got MODEL_TENSOR_ERROR

[error.log](https://github.com/user-attachments/files/17162639/1.log)

**Comment by yufeiy** [comment]
this OP inceptionV3_InceptionV3_Conv2d_1a_3x3_Conv2D_stride is already supported in current QNN SDK. You can downgrade the SDK version to v2.20.0 to be incompatible with the program or unregister this op in QNN backend.
