### ISSUE TITLE
demo_qnn疑问

### ISSUE THREAD

**Issue by ustcsq** [UbiquitousLearning/mllm#175]
您好，在运行demo_qnn的时候，设备是小米14，结果如下图：
![企业微信截图_17304526071171](https://github.com/user-attachments/assets/3d965b2d-8f88-471c-82e6-61fe201c28f7)
有一些些疑问，求助一下
1. npu部分是只输出了℉，这个是正常的嘛，还是有哪里误操作了
2. 析构的时候有报错Cannot destroy HexNN graph as PrepreLib is not loaded，运行的时候有设置LD_LIBRARY_PATH和ADSP_LIBRARY_PATH

非常感谢！

**Comment by oreomaker** [comment]
> @oreomaker 你好，我也遇到了同样的情况 ![image](https://private-user-images.githubusercontent.com/183582405/393790766-3ed5d5f7-bfb6-4515-a5b3-895ddf7197dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDA5NzQsIm5iZiI6MTczMzc0MDY3NCwicGF0aCI6Ii8xODM1ODI0MDUvMzkzNzkwNzY2LTNlZDVkNWY3LWJmYjYtNDUxNS1hNWIzLTg5NWRkZjcxOTdkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMDM3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDZlYjA4YTZmN2NjZjhiZTg0ZjRmOGMzMzkzNjFjZWNiZGNlOWI5NmYzMzdhOTcxYmY2OGQ0NzU5ZTc4N2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e9hqU5KQqEy6cILqSrUvfgbb5-RwAIOKm50geslWKn0) ，当我在执行run_phonelm_qnn.sh和run_qwen_qnn.sh的时候，都出现了这种情况。我打开了Debug，发现报错代码 ![image](https://private-user-images.githubusercontent.com/183582405/393790583-61a95503-03e9-4b84-bc1c-458b29df2d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDA5NzQsIm5iZiI6MTczMzc0MDY3NCwicGF0aCI6Ii8xODM1ODI0MDUvMzkzNzkwNTgzLTYxYTk1NTAzLTAzZTktNGI4NC1iYzFjLTQ1OGIyOWRmMmQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMDM3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjhlNDA5YjNkNDk1MTIwM2E5MGQyOGI1YjQ2OWQ2MzJmN2M3ZjI1NzI1MjUzZjk4MDBmNjUxM2ZkZjY0OTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j2irzPTbtcLlyCsrGWQ0QcmrChf-bCwsjc1aETh2-78)。所以说，这个问题解决了吗，或者说该怎么解决？

目前还未解决，问题出现在程序退出释放qnn资源的过程。

**Comment by Smallhucaptain** [comment]
那岂不是在这个问题解决之前，没办法用这个框架去利用NPU进行推理了么？还是说推理过程已经结束，只是最后的退出释放过程出现问题？

**Comment by Smallhucaptain** [comment]
@oreomaker

**Comment by oreomaker** [comment]
> 那岂不是在这个问题解决之前，没办法用这个框架去利用NPU进行推理了么？还是说推理过程已经结束，只是最后的退出释放过程出现问题？

你好，该报错内容为推理结束程序退出时产生。

**Comment by Smallhucaptain** [comment]
@oreomaker 好的，我在Error when running main_qwen_npu #203这个问题下面也遇到了问题，可以帮我解答一下吗？麻烦了！
