### ISSUE TITLE
Error when running main_qwen_npu

### ISSUE THREAD

**Issue by xtst** [UbiquitousLearning/mllm#203]
I run `./main_qwen_npu -s 64 -c 1` with all environment done. It load the model but some error occurs
```.
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:121] Backend: libQnnHtp.so
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:148] qnn-backend    build version: v2.16.4.231110151339_60331
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:149] Backend        build version: v2.20.0.240223161333_83920
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:172] Initialize Backend Returned Status = 0
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:636] Registered Op Package: libQnnLLaMAPackage_CPU.so and interface provider: LLaMAPackageInterfaceProvider
[INFO] Fri Nov 29 00:02:26 2024 [/home/x/mllm/src/backends/qnn/QNNBackend.cpp:636] Registered Op Package: libQnnLLaMAPackage_HTP.so and interface provider: LLaMAPackageInterfaceProvider
Load model: 1.38504 s
Load model: 0.353427 s
Load model: 1.31225 s
  3118.1ms [ ERROR ] Number of input elements 524288 does not match number of output elements 0.

  3118.2ms [ ERROR ] Op specific validation failed.

     0.0ms [ ERROR ]  <E> validateNativeOps master op validator model.layers.0.self_attn.ires_split-00_view_:qti.aisw:Reshape failed 3110

     0.0ms [ ERROR ]  <E> QnnBackend_validateOpConfig failed 3110

     0.0ms [ ERROR ]  <E> Failed to validate op model.layers.0.self_attn.ires_split-00_view_ with error 0xc26

[ ERROR ] QnnModel::addNode() validating node model.layers.0.self_attn.ires_split-00_view_ failed.
[ ERROR ] qnnModels_[qnnModelIndex_].addNode( QNN_OPCONFIG_VERSION_1, name.c_str(), packageName.c_str(), nodeType.c_str(), paramsPtr, params.size(), inputTensorNames, inputTensorNames.size(), outputTensors.data(), outputTensors.size() ) expected MODEL_NO_ERROR, got MODEL_GRAPH_ERROR
     0.0ms [ ERROR ]  <E> Cannot destroy HexNN graph as PrepreLib is not loaded

     0.0ms [ ERROR ]  <E> Failed to destroy hexNNGraphHandle 0xe7e3e000

     0.0ms [ ERROR ]  <E> Failed to clean up hexNNGraph in htpGraph 0x1 with error 1000

     0.0ms [WARNING]  <W> Final cleanup: failed to clean up backend.

     0.0ms [WARNING]  <W> sg_stubPtr is not null, skip loadRemoteSymbols
```

**Comment by oreomaker** [comment]
In main_qwen_npu.cpp, the chunk size is set manually to 256, so the seq should be multiple of 256. The configurable chunk size is implemented in demo_phonelm_npu.cpp while not supported in main_qwen_npu.cpp yet.

**Comment by oreomaker** [comment]
> @oreomaker 你好，我不知道我理解的对不对，就是说在main_qwen_npu.cpp中，他的输入序列长度必须是256的倍数么？在demo_phonelm_npu.cpp中则不限制序列长度？那么 ![image](https://private-user-images.githubusercontent.com/183582405/393793296-7756f33d-a583-458d-9f70-11a3f606cc3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDE5ODQsIm5iZiI6MTczMzc0MTY4NCwicGF0aCI6Ii8xODM1ODI0MDUvMzkzNzkzMjk2LTc3NTZmMzNkLWE1ODMtNDU4ZC05ZjcwLTExYTNmNjA2Y2MzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxMDU0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2M3ZjUwNDc3Zjg3Njg4ZTliZmVmYTYzMmU3OTcxMWJmMTkyMmE0ZmI0NjJiMjdjMmNjMmIyYTU4NzU1OGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aRgtnNmCrenjgd5OUG9lF5C9KsNgu3xnHGE_wev8BsI) 您们的这个执行demo又是如何实现的呢？是有什么设置上的修改还是怎么回事？ 麻烦了！

demo_qwen_npu和demo_phonelm_npu中增加了对chunk大小的配置，以及modeling文件中初始化的设置。

**Comment by Smallhucaptain** [comment]
@oreomaker 那么我该具体怎么做，才能让main_qwen_npu这个执行程序执行起来呢，增加它的输入序列长度到256的倍数？或者是修改一些其他的设置？

**Comment by oreomaker** [comment]
程序参数-s设置为256的倍数。

**Comment by Smallhucaptain** [comment]
@oreomaker 我今天上午分别用`-s=64、s=256、s=512`试了一下，发现确实当`-s=64、s=256`会出现楼主的这种错误，当`-s=512`时可以执行。但是在执行过程中，有一些问题：  

1. 我的模型加载速度相比其他人要慢很多,这个模型加载的速度由什么决定的呢？这下面是`-s=64、s=256、s=512`时的模型加载时间。

```
Load model: 2.27829 s	Load model: 1.94235 s	Load model: 1.61744 s
Load model: 1.1641 s	Load model: 0.750613 s	Load model: 1.01211 s
Load model: 4.07216 s	Load model: 3.50691 s	Load model: 7.32078 s
```

2. 虽然当`-s=512`时可以执行，但是执行的速度非常慢，这个又是因为什么原因呢？

我将输入日志贴在下面。
[main_qwen_npu_s512.log](https://github.com/user-attachments/files/18073135/main_qwen_npu_s512.log)

**Comment by oreomaker** [comment]
> @oreomaker 我今天上午分别用`-s=64、s=256、s=512`试了一下，发现确实当`-s=64、s=256`会出现楼主的这种错误，当`-s=512`时可以执行。但是在执行过程中，有一些问题：
> 
> 1. 我的模型加载速度相比其他人要慢很多,这个模型加载的速度由什么决定的呢？这下面是`-s=64、s=256、s=512`时的模型加载时间。
> 
> ```
> Load model: 2.27829 s	Load model: 1.94235 s	Load model: 1.61744 s
> Load model: 1.1641 s	Load model: 0.750613 s	Load model: 1.01211 s
> Load model: 4.07216 s	Load model: 3.50691 s	Load model: 7.32078 s
> ```
> 
> 2. 虽然当`-s=512`时可以执行，但是执行的速度非常慢，这个又是因为什么原因呢？
> 
> 我将输入日志贴在下面。 [main_qwen_npu_s512.log](https://github.com/user-attachments/files/18073135/main_qwen_npu_s512.log)

运行速度和你的设备配置有关，qnn目前会占用大量内存资源，暂时无法解决，在内存小于16GB时会导致频繁swap降低cpu运行速度。

**Comment by Smallhucaptain** [comment]
好的，麻烦了！
