### ISSUE TITLE
"merge file is broken" in "demo_qwen2.5_npu"

### ISSUE THREAD

**Issue by KAIWEILIUCC** [UbiquitousLearning/mllm#205]
When I run the "demo_qwen2.5_npu", there will be an error "merge file is broken".

**Comment by qxuan512** [comment]
Hello, I'm also having this problem, how did you solve it

**Comment by zeng-zc** [comment]
I encounter the same problem on xiaomi 15. How do you fix it? Thanks.

**Comment by zeng-zc** [comment]
Solved!
refer to: https://github.com/UbiquitousLearning/mllm/issues/133#issuecomment-2320142926
