### ISSUE TITLE
CPUBackend memory leak in Matmul 

### ISSUE THREAD

**Issue by JYLeeLYJ** [UbiquitousLearning/mllm#208]
https://github.com/UbiquitousLearning/mllm/blob/acdfc6c93f8ef617daad9b9e2974e778009b1930/src/backends/cpu/compute/Matmul.cpp#L73

This unique_ptr will not free host_ptr_ cause ```~Tensor()``` is default deconstructor .

Recommended  RAII :
```c++
    Tensor to{};
    struct Finally{
        Tensor & tensor ; 
        ~Finally() { tensor.free() ; }
    }on_exit{to};

    if (not_vec_dot_type) {
        // convert x.dtype to vec_dot_type
        // so that we can use vec_dot to calculate dot product
        assert(src0_dtype == MLLM_TYPE_F32); // x should be fp32
        to = Tensor(src0->shape());

```

**Comment by chenghuaWang** [comment]
Thank you for your work, we will fix this bug in the upcoming work. 👍
