### ISSUE TITLE
 [ ERROR ] Number of input elements 524288 does not match number of output elements 0.(Snapdragon 8 Elite)

### ISSUE THREAD

**Issue by Dantetang** [UbiquitousLearning/mllm#211]
When I execute on the Snapdragon 8 Elite, I encounter the following error:
I followed the instructions strictly as outlined in the run_qwen_npu.sh script. I used the libraries related to V79 instead of V75

/main_qwen_npu -s 64 -c 1
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:121] Backend: libQnnHtp.so
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:148] qnn-backend    build version: v2.16.4.231110151339_60331
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:149] Backend        build version: v2.25.9.240826120644_20452
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:172] Initialize Backend Returned Status = 0
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:636] Registered Op Package: libQnnLLaMAPackage_CPU.so and interface provider: LLaMAPackageInterfaceProvider
[INFO]  Dec 11  2024 [/home/mllm/src/backends/qnn/QNNBackend.cpp:636] Registered Op Package: libQnnLLaMAPackage_HTP.so and interface provider: LLaMAPackageInterfaceProvider
Load model: 5.68148 s
Load model: 2.33918 s
Load model: 3.86221 s
 12063.4ms [ ERROR ] Number of input elements 524288 does not match number of output elements 0.

 12063.4ms [ ERROR ] Op specific validation failed.

     0.0ms [ ERROR ]  <E> validateNativeOps master op validator model.layers.0.self_attn.ires_split-00_view_:qti.aisw:Reshape failed 3110

     0.0ms [ ERROR ]  <E> QnnBackend_validateOpConfig failed 3110

     0.0ms [ ERROR ]  <E> Failed to validate op model.layers.0.self_attn.ires_split-00_view_ with error 0xc26

[ ERROR ] QnnModel::addNode() validating node model.layers.0.self_attn.ires_split-00_view_ failed.
[ ERROR ] qnnModels_[qnnModelIndex_].addNode( QNN_OPCONFIG_VERSION_1, name.c_str(), packageName.c_str(), nodeType.c_str(), paramsPtr, params.size(), inputTensorNames, inputTensorNames.size(), outputTensors.data(), outputTensors.size() ) expected MODEL_NO_ERROR, got MODEL_GRAPH_ERROR

**Comment by oreomaker** [comment]
In main_qwen_npu.cpp, the chunk size is set manually to 256, so the 'seq' argument should be multiple of 256. The error is caused by this.
As for the 8 Elite, we have not tested the QNN library on it, which may have issues with compatibility.

**Comment by Dantetang** [comment]
Thank you. The issue with "Number of input elements 524288 does not match number of output elements 0" has been resolved. The current issue is the compatibility problem with V79. Similar to the one described in https://github.com/UbiquitousLearning/mllm/issues/178.
