### ISSUE TITLE
what's happen if I use mllm in Snapdragon 8 gen 2 ? 

### ISSUE THREAD

**Issue by liangy001** [UbiquitousLearning/mllm#212]
I'm very interested in MLLM. It's so amazing! Unfortunately, I only have a phone with Snapdragon 8 Gen 2 in hand. So, if I want to use MLLM to deploy an LLM on it, can I succeed?

**Comment by oreomaker** [comment]
The current version of QNN library including htp(NPU lib) and QNN op package is set to v75, which is the Hexagon Arch of Snapdragon 8 Gen3. You can run the CPU only examples on 8 Gen 2. Maybe changing the libraries and op package to v73 will work, but it  hasn't been tested yet.
