### ISSUE TITLE
Android app crash while Image Reading

### ISSUE THREAD

**Issue by Vinaysukhesh98** [UbiquitousLearning/mllm#74]
Fail To Load Models! Please Check if models exists at /sdcard/Download/model and restart 
but i have  copied model in that location. still getting same error message what would be the reason.

**Comment by lx200916** [comment]
Hi,
1. Currently the android lib is only shipped with LLaMA and Fuyu support, please make sure your model files are supported.
2. Could you double check the file is renamed properly according to [This notice](https://ubiquitouslearning.github.io/mllm_website/introduction/getstarted/#build-for-android-demo-app)? it would be better if you attach a screenshot or else to show the file tree structure of your `/sdcard/Download/model`.

**Comment by Vinaysukhesh98** [comment]
for llama it was detecting ,, but Fuyu load was not detecting what could be the reason.

**Comment by Vinaysukhesh98** [comment]
while loading fuyu app is getting crashed getting below errors: 

 FATAL EXCEPTION: main
                                                                                                    Process: org.saltedfish.chatbot, PID: 10488
                                                                                                    java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

Process is going to kill itself!
                                                                                                    java.lang.Exception
                                                                                                    	at android.os.Process.killProcess(Process.java:1356)
                                                                                                    	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:174)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
                                                                                                    	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)

**Comment by lx200916** [comment]
Uh... It seems something wrong about the UI framework. What kind of device you are testing on?

**Comment by Vinaysukhesh98** [comment]
> Uh... It seems something wrong about the UI framework. What kind of device you are testing on?

Snapdragon 8 gen3 (xiaomi14)

**Comment by lx200916** [comment]
Opps... It seems fine on our testing devices (of same model). We may need some time to investigate it.😂

**Comment by Vinaysukhesh98** [comment]
> Opps... It seems fine on our testing devices (of same model). We may need some time to investigate it.😂

okay.

**Comment by lx200916** [comment]
Hi, we tried to reproduce the bug but sadly failed. Could you double check the `model` file tree?
![1712632741666](https://github.com/UbiquitousLearning/mllm/assets/44310445/511eaca9-f4f6-4267-8ce1-7442632320f7)

**Comment by Vinaysukhesh98** [comment]
hi @lx200916 , could able to load the model , but app is getting crashed after passing image.

**Comment by lx200916** [comment]
Understood. Could you attach the image file here? I guess maybe something wrong about the file size or PreProcessors.

**Comment by yirongjie** [comment]
The input image needs to be 3-channel (RGB),  @Vinaysukhesh98 you need to check if it is 4-channel (RGBA)

**Comment by Vinaysukhesh98** [comment]
> Understood. Could you attach the image file here? I guess maybe something wrong about the file size or PreProcessors.

https://github.com/UbiquitousLearning/mllm/blob/main/assets/dog_image.jpg

**Comment by Vinaysukhesh98** [comment]
> The input image needs to be 3-channel (RGB), @Vinaysukhesh98 you need to check if it is 4-channel (RGBA)

can you please help me with more info or any steps to resolve.
