### ISSUE TITLE
improve examples

### ISSUE THREAD

**Issue by zhehaoxu** [UbiquitousLearning/mllm#80]
don't use fixed image path in demo, add a new parameter, like:

`cmdParser.add<string>("image", 'i', "specify mllm image path", false, "../assets/cat.jpg");`

**Comment by yirongjie** [comment]
Thank you for your suggestion. We will consider adding a new parameter in files like [demo_vit.cpp](https://github.com/UbiquitousLearning/mllm/blob/main/examples/demo_vit.cpp).
