### ISSUE TITLE
Detailed Android smart phone model and configuration

### ISSUE THREAD

**Issue by baimuchu** [UbiquitousLearning/mllm#82]
Can you provide some information about the phone model (like XIAOMI 11) and the details of the configuration?

**Comment by lx200916** [comment]
Hi, the exact spec of the phone in our demo video is Xiaomi14(Snapdragon 8Gen3,16GB).

**Comment by baimuchu** [comment]
Thank you very much! And you can also mention such information, it is important for reproduce.
