### ISSUE TITLE
App download link cannot be successfully accessed

### ISSUE THREAD

**Issue by jzyztzn** [UbiquitousLearning/mllm#84]
This is a great job, but now the link doesn't seem to work properly, Could you update the link? I'd like to try it out.
[an example app](https://github.com/UbiquitousLearning/mllm/android)

**Comment by lx200916** [comment]
Sorry for the inconvenience 😂 We have updated the link and now it points to the sub-folder `android`. 
Thanks for your support and please let us know if anything else not working.😁

**Comment by jzyztzn** [comment]
Thank you very much for your reply, I followed the tutorial to compile apk successfully.😁 Because my phone is older，I tried the qwen-0.5 model，(only change qwen model and vocab name to llama_2.mllm and vocab.mllm). Then I type ”你好“，the chat model recover is ”<unk><unk>  ...  <unk><unk> “. May I ask what files I need to modify in order to achieve Chinese dialogue？

**Comment by jzyztzn** [comment]
😁Very valuable advice, I will try it again later. I used your qwen1.5-0.5B model [here](https://huggingface.co/mllmTeam/qwen-1.5-0.5b-mllm).
