### ISSUE TITLE
[Question] Does this demo support mediatek neuropilot?

### ISSUE THREAD

**Issue by AkaneTan** [UbiquitousLearning/mllm#96]
Does this demo suppot mediatek neuropilot? Saw neuropilot in the NPU chat from your essay.
![image](https://github.com/user-attachments/assets/ccb2471c-80f9-4256-8cb3-8a2810006855)

**Comment by lx200916** [comment]
Sorry mllm does not support neuropilot, only some of Qualcomm NPUs supported.

**Comment by AkaneTan** [comment]
Thank you for checking up.
